name: proyecto-devops
services:
   Tarea3:
     image: localhost:8082/proyecto-devops
     restart: always
     ports:
      - 3000:3000
     volumes:
      - /tmp/ficheros-contenedor:/var/ficheros
     environment:
      - NODE_ENV=development
     secrets:
      - api-key
secrets:
    api-key:
      file: api-key.txt