pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                docker {
                    image 'node:20.11.1-alpine3.19'
                    reuseNode true
                }
            }
            stages {
                stage('instalar dependencias') {
                    steps {
                        sh "npm install"
                    }
                }
                stage('ejecutar tet') {
                    steps {
                        sh 'npm run test'
                    }
                }
                stage('hacer build') {
                    steps {
                        sh 'npm run build'
                    }
                }
            }
        }
        stage('delivery docker') {
            steps {
                script {
                    docker.withRegistry('http://localhost:8082', 'nexus-key') {
                        sh 'docker build -t localhost:8082/proyecto-devops .'
                        sh "docker tag localhost:8082/proyecto-devops localhost:8082/proyecto-devops:${env.BUILD_NUMBER}"
                        sh 'docker push localhost:8082/proyecto-devops'
                        sh "docker push localhost:8082/proyecto-devops:${env.BUILD_NUMBER}"
                    }
                }
            }
        }
    }
}
